### ISSUE TITLE
rho dim is correct?

### ISSUE THREAD

**Issue by jeong-tae** [amasky/ram#7]
https://github.com/amasky/ram/blob/master/ram.py#L128

maybe the rho has [B, C * n_scales, size, size] dim.
But the network applies fully connected layer: [C * n_scales * size, * size], not conv2d.
although the number of parameters are same, the operation can't be applied

How can it works properly for the fc operation?

**Comment by amasky** [comment]
Hi jeong-tae!
In Chainer, as far as I remember, 4-axis data are automatically converted into 2 axis when we feed conv2d data into FC layers.

**Comment by jeong-tae** [comment]
oh, that's very useful! thx for the reply!
